name: "WLEmptyState CI"

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - '*'

jobs:
  iOS:
    runs-on: macOS-latest
    strategy:
      matrix:
        destination: ["OS=14.0,name=iPhone 11 Pro"]
    steps:
    - uses: actions/checkout@master
    - name: Set xcode Version
      run: sudo xcode-select -s /Applications/Xcode_12.app
    - name: Install Dependencies
      run: |
        cd Example
        pod install --repo-update
      shell: bash
    - uses: ty0x2333/cocoapods-action@master
      with:
        workspace: Example/WLEmptyState.xcworkspace
        scheme: WLEmptyState-Example
        additional_build_params: -destination "${{ matrix.destination }}"
        additional_lint_params: --private
